name: ecvm
mail: tim@electriccitizen.com
slogan: ''
page:
  403: ''
  404: /search404
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: oFGejEEA5thoklyMT_5vOvqJFtP4YzOvl3HxRH4jmC8
uuid: 1152b39b-e093-43fa-ab36-a0dccaafb39e
